# Environment options
width: 320
height: 320
ball: 2.0
ball_size: 4.0
snell: 2.0
snell_width: 160.0
snell_change: 0
snell_visible: "none"
#no_refraction:  # comment out to turn off
#uniform_speed:  # comment out to turn off
paddle_speed: 2.0
paddle_length: 40
paddle_angle: 70
state: "binary"
update_prob: 0.4

# Model and training options
episodes: 4000
learning_rate: 1e-4
network: dqn_pong_model
replay: 100_000
#rankbased: # comment out to turn off
#priority: # comment out to turn off
#pretrain:  # comment out to turn off

# File control options
#resume:  # comment out to turn off
#checkpoint: dqn_pong_model
#history: history.p
