# Environment options
width: 1280
height: 1280
ball: 8.0
ball_size: 16.0
snell: 8.0
snell_width: 640.0
snell_change: 0
snell_visible: "none"
#no_refraction:  # comment out to turn off
#uniform_speed:  # comment out to turn off
paddle_speed: 8.0
paddle_length: 160
paddle_angle: 70
state: "binary"
update_prob: 0.4

# Model and training options
episodes: 4000
learning_rate: 1e-4
network: dqn_pong_model
replay: 100_000
#rankbased: # comment out to turn off
#priority: # comment out to turn off
#pretrain:  # comment out to turn off

# File control options
#resume:  # comment out to turn off
#checkpoint: dqn_pong_model
#history: history.p
