width: 80
height: 80
ball: 2.0
snell: 2.0
snell_width: 20.0
paddle_speed: 3.0
paddle_length: 15
learning_rate: 1e-4
update_prob: 0.2
episodes: 4000
#resume: False
#checkpoint: dqn_pong_model
#history: history.p
#pretrain: False