width: 160
height: 160
ball: 3.0
snell: 3.0
paddle_speed: 3.0
paddle_length: 45
paddle_angle: 89
learning_rate: 1e-4
update_prob: 0.4
episodes: 2100  # ended after 1900 episodes
resume:
checkpoint: ../experiments/19/dqn_pong_model
history: ../experiments/19/history.p
network: dqn_pong_model
#pretrain: False