width: 160
height: 160
ball: 1.0
snell: 2.0
paddle_speed: 1.0
paddle_length: 45
paddle_angle: 89
learning_rate: 1e-4
update_prob: 0.2
episodes: 4000
#resume:  # comment out to turn off
#checkpoint: dqn_pong_model
#history: history.p
network: dqn_pong_model
#pretrain:  # comment out to turn off