width: 160
height: 160
ball: 3.0
snell: 2.0
paddle_speed: 3.0
paddle_length: 45
learning_rate: 1e-4
update_prob: 0.2
episodes: 4000
resume:
checkpoint: ../experiments/baseline-1-t3/dqn_pong_model
history: ../experiments/baseline-1-t3/history.p
