width: 80
height: 80
ball: 1.5
ball_size: 1.0
snell: 1.5
snell_width: 20.0
snell_change: 0
snell_visible: "none"
paddle_speed: 1.5
paddle_length: 22.5
paddle_angle: 45
learning_rate: 1e-4
update_prob: 0.2
episodes: 4000
#resume:  # comment out to turn off
#checkpoint: dqn_pong_model
#history: history.p
network: dqn_pong_model
#pretrain:  # comment out to turn off
state: "binary"
replay: 100_000
#priority: # comment out to turn off
#rankbased: # comment out to turn off